name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: demo-app
          organization: my-org
          token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [build, sonar]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        env:
          TF_VAR_kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Plan Terraform Deployment
        run: terraform plan
        env:
          TF_VAR_kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve
        env:
          TF_VAR_kubeconfig: ${{ secrets.KUBECONFIG }}
